### ISSUE TITLE
Provide new parameter to configure default behavior for empty `User-Agent`

### ISSUE THREAD

**Issue by gunturaf** [krakendio/krakend-botdetector#10]
The current implementation in this line will not mark the request as a "bot" request for the non-LRU implementation (which also affect the LRU implementation):
https://github.com/krakendio/krakend-botdetector/blob/dd4c1ed20c7b30850e5a30651748c9468539b358/detector.go#L68-L70

should we provide a new parameter to configure this behavior while still retaining the existing not-bot behavior? maybe something like `empty_user_agent_is_bot` (defaults to false)

**Comment by kpacha** [comment]
Thanks for the proposal!
