### ISSUE TITLE
Replace whitelist and blacklist terms

### ISSUE THREAD

**Issue by alombarte** [krakendio/krakend-botdetector#2]
Terms blacklist and whitelist are metaphoric (not descriptive) and have racial connotations.

Let's use `deny` and `allow` instead.

**Comment by alombarte** [comment]
Docs updated: https://github.com/devopsfaith/krakend-documentation/pull/82/commits/0f73291414a6c52ef5e40b7672923126081c5646#diff-3738c68375993b92287517d6768302d6

**Comment by kpacha** [comment]
done at v2 branch. waiting for the final release to close this
